version: '3'
services:
  vite-react-app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
